version: "3.9"

services:
  hazel:
    image: hazelcast/hazelcast
    env_file: .env
    volumes:
      - $PWD/config-ext/:/opt/hazelcast/config-ext/:ro

  hazel_1:
    extends: hazel
    ports:
      - 5701:5701

  hazel_2:
    extends: hazel
    ports:
      - 5702:5701

  hazel_3:
    extends: hazel
    ports:
      - 5703:5701

  hazel_management_center:
    depends_on:
      - hazel_1
      - hazel_2
      - hazel_3
    image: hazelcast/management-center
    ports:
      - 8080:8080

  client:
    depends_on:
      - hazel_1
      - hazel_2
      - hazel_3
    links:
      - hazel_1
      - hazel_2
      - hazel_3
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - arg1
